export { sendError, sendLog } from "./sentry"
export { logout } from "./logout"
export { auth, firestore, functions, storage } from "./firebase"
export { setAdmin } from "./functions"
export { storeName, isDevMode, isFirebaseEmulator } from "./env"
