export { sendError, sendLog } from "./log"
export { logout } from "./auth"
export { auth, firestore, functions, storage } from "./firebase"
export { setAdmin } from "./functions"
export { storeName, isDevMode, isFirebaseEmulator } from "./env"
